SELECT 'CREATE DATABASE project' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'project');
CREATE USER pguser WITH PASSWORD 'pgpassword';
GRANT ALL PRIVILEGES ON DATABASE project TO pguser;